import type { PresetDefinition, SceneConfig } from '../types/config';

export const defaultSceneConfig: SceneConfig = {
  seed: 2817,
  background: {
    type: 'gradient',
    topColor: '#f7f5f0',
    bottomColor: '#ece9e1',
    washColor: '#faf7f1',
    imageSrc: '',
  },
  rays: {
    enabled: true,
    originX: 0.92,
    originY: 0.54,
    rotation: 180,
    fanAngle: 74,
    startDistance: 0,
    endDistance: 1.32,
    opacity: 0.74,
    startBlur: 0.08,
    blur: 0.94,
    driftAmount: 0,
    driftSpeed: 0,
    rotationSpeed: 1,
    pausedWhileParticlesMove: false,
    bands: [
      { id: 'band-1', color: '#87a1e6', offset: 0.0, weight: 1.02, softness: 0.96 },
      { id: 'band-2', color: '#9ddfdc', offset: 0.16, weight: 0.98, softness: 0.98 },
      { id: 'band-3', color: '#bfe2a5', offset: 0.33, weight: 1, softness: 1 },
      { id: 'band-4', color: '#eadc98', offset: 0.5, weight: 1.02, softness: 1 },
      { id: 'band-5', color: '#e2b28d', offset: 0.66, weight: 0.96, softness: 0.98 },
      { id: 'band-6', color: '#d8abc5', offset: 0.82, weight: 0.92, softness: 0.96 },
      { id: 'band-7', color: '#b6b9e5', offset: 1.0, weight: 0.9, softness: 0.96 },
    ],
  },
  particles: {
    enabled: true,
    count: 26,
    minSize: 0.4,
    maxSize: 1.1,
    minSpeed: 0.03,
    maxSpeed: 0.12,
    opacity: 0.04,
    twinkle: 0.14,
    spread: 0.42,
    directionRandomness: 0.14,
    direction: 'into-apex',
    color: '#ffffff',
  },
  postprocessing: {
    softness: 0.7,
    globalBlur: 0.22,
    bloom: 0,
    grain: 0.01,
    vignette: 0,
    brightness: 1,
  },
  export: {
    width: 1080,
    height: 1080,
    duration: 6,
    fps: 30,
  },
};

export const presets: PresetDefinition[] = [
  {
    id: 'classic-rainbow-prism',
    name: 'Classic Rainbow Prism',
    kind: 'builtin',
    config: defaultSceneConfig,
  },
  {
    id: 'pastel-soft-spectrum',
    name: 'Pastel Soft Spectrum',
    kind: 'builtin',
    config: {
      ...defaultSceneConfig,
      seed: 7342,
      background: {
        ...defaultSceneConfig.background,
        topColor: '#f8f4fa',
        bottomColor: '#eeebe9',
        washColor: '#faf7fb',
      },
      rays: {
        ...defaultSceneConfig.rays,
        originX: 0.9,
        originY: 0.57,
        fanAngle: 70,
        opacity: 0.62,
        startBlur: 0.12,
        blur: 0.98,
        rotationSpeed: 1,
        pausedWhileParticlesMove: false,
        bands: [
          { id: 'band-1', color: '#b0bce8', offset: 0.0, weight: 1, softness: 1 },
          { id: 'band-2', color: '#c0e7ec', offset: 0.2, weight: 0.98, softness: 1 },
          { id: 'band-3', color: '#d7e8bc', offset: 0.4, weight: 0.96, softness: 1 },
          { id: 'band-4', color: '#f0e1b0', offset: 0.6, weight: 1, softness: 1 },
          { id: 'band-5', color: '#e8c8bd', offset: 0.8, weight: 0.94, softness: 0.98 },
          { id: 'band-6', color: '#d9c3e9', offset: 1.0, weight: 0.9, softness: 0.98 },
        ],
      },
      particles: {
        ...defaultSceneConfig.particles,
        count: 18,
        opacity: 0.03,
        direction: 'into-apex',
        color: '#ffffff',
      },
      postprocessing: {
        ...defaultSceneConfig.postprocessing,
        globalBlur: 0.1,
        bloom: 0,
      },
    },
  },
  {
    id: 'golden-refraction',
    name: 'Golden Refraction',
    kind: 'builtin',
    config: {
      ...defaultSceneConfig,
      seed: 1945,
      background: {
        ...defaultSceneConfig.background,
        topColor: '#f6f2ea',
        bottomColor: '#ece4d8',
        washColor: '#f8f3e5',
      },
      rays: {
        ...defaultSceneConfig.rays,
        originY: 0.56,
        fanAngle: 68,
        opacity: 0.7,
        startBlur: 0.06,
        blur: 0.9,
        rotationSpeed: 1,
        pausedWhileParticlesMove: false,
        bands: [
          { id: 'band-1', color: '#ecd78f', offset: 0.0, weight: 1.08, softness: 0.94 },
          { id: 'band-2', color: '#e6c58d', offset: 0.34, weight: 1, softness: 0.96 },
          { id: 'band-3', color: '#dda37f', offset: 0.68, weight: 0.94, softness: 0.98 },
          { id: 'band-4', color: '#f3ebbc', offset: 1.0, weight: 0.88, softness: 1 },
        ],
      },
      particles: {
        ...defaultSceneConfig.particles,
        count: 20,
        opacity: 0.035,
        direction: 'into-apex',
        color: '#fff6de',
      },
      postprocessing: {
        ...defaultSceneConfig.postprocessing,
        bloom: 0,
        brightness: 0.99,
      },
    },
  },
  {
    id: 'duotone-brand-glow',
    name: 'Brand-like Duotone Refraction',
    kind: 'builtin',
    config: {
      ...defaultSceneConfig,
      seed: 9051,
      background: {
        ...defaultSceneConfig.background,
        topColor: '#f2f5f7',
        bottomColor: '#e7e8e3',
        washColor: '#f5f6f2',
      },
      rays: {
        ...defaultSceneConfig.rays,
        fanAngle: 56,
        opacity: 0.66,
        startBlur: 0.04,
        blur: 0.84,
        rotationSpeed: 1,
        pausedWhileParticlesMove: false,
        bands: [
          { id: 'band-1', color: '#90b9e6', offset: 0.0, weight: 1.14, softness: 0.96 },
          { id: 'band-2', color: '#b9ddd0', offset: 1.0, weight: 0.98, softness: 0.98 },
        ],
      },
      particles: {
        ...defaultSceneConfig.particles,
        count: 16,
        opacity: 0.025,
        direction: 'into-apex',
        color: '#f4fbff',
      },
      postprocessing: {
        ...defaultSceneConfig.postprocessing,
        bloom: 0,
        globalBlur: 0.06,
        brightness: 1,
      },
    },
  },
];
